# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Open Banking CDS Toolkit Documentation
site_description: Documentation for WSO2 Open Banking CDS Toolkit
site_author: WSO2
site_url: https://cds.ob.docs.wso2.com/en/latest/

# Repository
repo_name: wso2/docs-ob-toolkit-cds
repo_url: https://github.com/wso2/docs-ob-toolkit-cds
edit_uri: https://github.com/wso2/docs-ob-toolkit-cds/edit/main/en/docs/

# Copyright
copyright: WSO2 Open Banking CDS Toolkit - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Navigation
nav:
  - 'Home': index.md
  - 'Get Started':
    - 'Open Banking': get-started/open-banking.md
    - 'Open Banking Requirements': get-started/open-banking-requirements.md
    - 'Regulations and Standards': get-started/regulations-and-standards.md
    - 'WSO2 Open Banking CDS Toolkit': get-started/wso2-open-banking-cds-toolkit.md
    - 'About this Release': get-started/about-this-release.md
    - 'Quick Start Guide':
      - 'Get Started': get-started/quick-start-guide.md
      - 'Set up Toolkits': get-started/set-up-toolkits.md
      - 'Configure Users and Roles': get-started/configure-users-and-roles.md
      - 'Configure SMS OTP Authenticator': get-started/configure-sms-otp-authenticator.md
      - 'Dynamic Client Registration': get-started/dynamic-client-registration.md
      - 'Tryout Flow': get-started/try-out-flow.md
      - 'Data Publishing': get-started/data-publishing-try-out.md
  - 'Install and Setup':
    - 'Prerequisites': install-and-setup/prerequisites.md
    - 'Setting up servers': install-and-setup/setting-up-servers.md
    - 'Setting up databases': install-and-setup/setting-up-databases.md
    - 'Configuring Identity Server': install-and-setup/configuring-identity-server-for-ob.md
    - 'Configuring API Manager': install-and-setup/configuring-api-manager-for-ob.md
    - 'Configuring Users and Roles': install-and-setup/configuring-users-and-roles.md
    - 'Configuring SMS OTP Authenticator': install-and-setup/configuring-sms-otp-authenticator.md
    - 'Upgrading the solution': install-and-setup/upgrading-the-solution.md
       #- 'Upgrading the solution': install-and-setup/upgrading-the-solution/upgrading-the-solution.md
       #- 'Upgrading to API Manager 3.2.0': install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-320.md
       #- 'Upgrading to Identity Server 5.11.0': install-and-setup/upgrading-the-solution/upgrading-wso2-identity-server.md
       #- 'Upgrading to API Manager 4.0.0': install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-400.md
       #- 'Open Banking Data Migration': install-and-setup/upgrading-the-solution/open-banking-data-migration.md
       #- 'Reporting Data Migration': install-and-setup/upgrading-the-solution/reporting-data-migration.md
       #- 'Modifications After Migration': install-and-setup/upgrading-the-solution/modifications-after-migration.md
  - 'Learn':
    - 'Consent Management':
       - 'Introduction': learn/consent-management.md
       - 'Consent Amendment History': learn/consent-amendment-history.md
    - 'Consent Authorization':
       - 'Introduction': learn/consent-authorization-intro.md
       - 'Pushed Authorization Endpoint': learn/pushed-authorization-endpoint.md
    - 'Token Authentication': learn/token-authentication.md
    - 'Dynamic Client Registration':
       - 'Introduction': learn/dynamic-client-registration.md
       - 'Configuration': learn/dynamic-client-registration-configuration.md
    - 'Consumer Authentication': learn/consumer-authentication.md
    - 'Metadata Cache Management': learn/metadata-cache-management.md
    - 'Administration API': learn/administration-api.md
    - 'Arrangement Revocation API': learn/arrangement-revocation-api.md
    - 'API Security':
       - 'Introduction': learn/api-security.md
       - 'Configuration': learn/api-security-configuration.md
    - 'Data Publishing':
       - 'Introduction': learn/data-publishing.md
       - 'Tryout': learn/data-publishing-tryout.md
    #- 'CDR Data Reporting': learn/cdr-data-reporting.md
    - 'Non Functional Requirements': learn/non-functional-requirements.md
    - 'Account Management':
        - 'Data Sharing for Business Nominated Representatives':
            - 'Introduction': learn/configuring-data-sharing-for-business-nominated-representatives.md
            - 'Configuration': learn/configuring-data-sharing-for-business-nominated-representatives-configuration.md
        - 'Disclosure Option Management':
            - 'Introduction': learn/disclosure-option-management.md
            - 'Configuration': learn/disclosure-option-management-configuration.md
        - 'Data Sharing for Secondary Users':
            - 'Introduction': learn/configuring-data-sharing-for-secondary-users.md
            - 'Configuration': learn/configuring-data-sharing-for-secondary-users-configuration.md
        - 'Ceasing Data Sharing for Secondary Users':
            - 'Introduction': learn/ceasing-data-sharing-for-secondary-users.md
            - 'Configuration': learn/ceasing-data-sharing-for-secondary-users-configuration.md
  - 'Try out':
    - 'Dynamic Client Registration': try-out/dynamic-client-registration-flow.md
    - 'Account and Transaction flow': try-out/account-and-transaction-flow.md
    - 'Administration API': try-out/admin-api.md
    - 'Arrangement Revocation API': try-out/arrangement-revocation-api-flow.md
    - 'Consent Manager': try-out/consent-manager.md
    - 'Consent Amendment History Retrieval': try-out/consent-amendment-history.md
    - 'Deploy Custom Throttling Policies': try-out/custom-throttling-policies.md
  - 'References':
    - 'Identity Server Configuration Catalog': references/config-catalog-is.md
    - 'API Manager Configuration Catalog': references/config-catalog-apim.md
    - 'Consent REST API': references/consent-rest-api.md
    - 'DCR REST API': references/dcr-rest-api.md
    - 'Application Info API': references/application-info-api.md
  - '': page-not-found.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - markdownextradata: {}
  - redirects:
      redirect_maps:
        'install-and-setup/upgrading-the-solution/upgrading-the-solution.md': 'https://cds.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
        'install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-320.md': 'https://cds.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
        'install-and-setup/upgrading-the-solution/upgrading-wso2-identity-server.md': 'https://cds.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
        'install-and-setup/upgrading-the-solution/upgrading-wso2-api-manager-400.md': 'https://cds.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
        'install-and-setup/upgrading-the-solution/open-banking-data-migration.md': 'https://cds.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
        'install-and-setup/upgrading-the-solution/reporting-data-migration.md': 'https://cds.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'
        'install-and-setup/upgrading-the-solution/modifications-after-migration.md': 'https://cds.ob.docs.wso2.com/en/latest/install-and-setup/upgrading-the-solution/'

# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 1.0.0
  nav_list:
    - Home
    - Get Started
    - Install and Setup
    - Learn
    - Try out